### PR TITLE
Disable Ascii in serialized json

### LINKED ISSUE #179: Escape Ascii Characters for Serialization and Regenerate Sample Data
The `jsons` library depends on `json`. One feature that we're not using is the `ensure_ascii=False`. This keeps the output in `unicode` not in `\uXXXX` sequences. 

Json documentation: https://docs.python.org/2/library/json.html#basic-usage
Jsons documentation https://github.com/ramonhagenaars/jsons/blob/aa565f530b3e72c5854cf11b10b1d90daa85f047/jsons/_dump_impl.py#L71

This is relevant for `electionguard.serializable` anywhere that `dump` or `dumps` from `jsons` is used. 

Add this property in and ensure use `make generate-sample-data` to regenerate the 5 ballot threshold and non threshold sets.

### PR DESCRIPTION
**Pull request by iadi7ya**
### Issue

Fixes #179 

### Description
*Please describe your pull request.*

### Testing
*Describe the best way to test or validate your PR.*

### Checklist
🚨Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

- [x] 🤔 **CONSIDER** adding a unit test if your PR resolves an issue.
- [x] ✅ **DO** check open PR's to avoid duplicates.
- [x] ✅ **DO** keep pull requests small so they can be easily reviewed.
- [x] ✅ **DO** build locally before pushing.
- [x] ✅ **DO** make sure tests pass.
- [x] ✅ **DO** make sure any new changes are documented.
- [x] ✅ **DO** make sure not to introduce any compiler warnings.
- [x] ❌**AVOID** breaking the continuous integration build.
- [x] ❌**AVOID** making significant changes to the overall architecture.

💚Thank you!

### CODE REVIEW

**Comment by keithrfung** [comment]
Why two PR's?

**Comment by iadi7ya** [comment]
> Why two PR's?

Created another fork. In previous make lint was not working.

**Comment by keithrfung** [comment]
Be sure you double check your version of `black` and `pylint`. We're using the latest.

**Comment by iadi7ya** [comment]
> Be sure you double check your version of `black` and `pylint`. We're using the latest.

black, version 20.8b1  and   pylint 1.8.3

**Comment by keithrfung** [comment]
You can run the lint manually `make lint`
OR
Run the auto correct: `pipenv run black .`

**Review by iadi7ya — COMMENTED** [review]
Hi @keithrfung All checks have passed. Thanks.

**Review by keithrfung — APPROVED** [review]
Looks good to me. We're going to have to change some sample data for this but nice to see it's so simple. We'll wait to pull this in until we slow down on some patches.

**Comment by iadi7ya** [comment]
> Looks good to me. We're going to have to change some sample data for this but nice to see it's so simple. We'll wait to pull this in until we slow down on some patches.

Thanks @keithrfung . I have run the ``make generate-sample-data`` and it has not produced any error.

**Pull request merged**
