### PR TITLE
Updated proof verification to False for encrypt default

### LINKED ISSUE #584: 🏎  Encrypt default should set proof verification to False
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Suggestion

Adjust `should_verify_proofs` to `False` as the default for the encrypt functions to allow for speed as opposed to thoroughness for default production system. This is to match the expectations on the C++ side as well. 

### Possible Implementation

The following lines would need to be updated:
https://github.com/microsoft/electionguard-python/blob/ec69dec9cc802824ba37d273b3ffebdf7f6af9fc/src/electionguard/encrypt.py#L161
https://github.com/microsoft/electionguard-python/blob/ec69dec9cc802824ba37d273b3ffebdf7f6af9fc/src/electionguard/encrypt.py#L243
https://github.com/microsoft/electionguard-python/blob/ec69dec9cc802824ba37d273b3ffebdf7f6af9fc/src/electionguard/encrypt.py#L412
https://github.com/microsoft/electionguard-python/blob/ec69dec9cc802824ba37d273b3ffebdf7f6af9fc/src/electionguard/encrypt.py#L496

Tests outside of bench for `encrypt` should also always ensure to pass True into these functions for `should_verify_proof`. Be sure to adjust comments where it mentions default is True.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by phershbe**
### Issue
https://github.com/microsoft/electionguard-python/issues/584

Fixes #584 

### Description
As described in the issue above, changed should_verify_proofs to False for the encrypt functions to allow for speed as opposed to thoroughness for default production system. Also changed comments to state that default is False for such cases.
Relating to those changes, changed tests outside of bench for encrypt to True for the same functions. I understood that I should do this for cases of succeeds but not cases of fails, but as I'm a new contributor and relatively new to open source, review of this would be appreciated.

### Testing
I tested the changes with "make test" and everything came back okay. I did that on my local environment and then made the same changes in GitHub since I was having trouble pushing my local changes back to GitHub, something with my personal access token I think, the changes are all the same as the changes which passed the tests though.

### CODE REVIEW

**Review by keithrfung — CHANGES_REQUESTED** [review]
Be sure to run `make auto-lint` and sign agreement.

**Comment by phershbe** [comment]
@keithrfung Okay, thank you, I signed the agreement and updated the auto-lint results. Was I correct in the way I updated the encrypt tests?

**Comment by phershbe** [comment]
@keithrfung I tried to update the file with auto-lint again, hopefully the test passes now

**Comment by phershbe** [comment]
@keithrfung The test failed in the the Full Test Suite & Coverage section of the Linux Check. The place where it failed seemed to be tests/property/test_decrypt_with_secrets.py. I didn't realize before now that the encrypt_selection and encrypt_contest functions are also tested there, although I didn't make any changes there before, so I suppose that it's related to that. I thought about adding should_verify_proofs there and trying again, but I'm hesitant to because the last tests ran for a long time before being cancelled, so maybe that was expensive or put a lot of pressure on the system or something. Let me know where to go from here.

**Comment by keithrfung** [comment]
@phershbe I think that was a false negative. I've been noticing some weirdness with one of the CI tests.

**Review by keithrfung — CHANGES_REQUESTED** [review]
There are more test references `encrypt_ballot`, `encrypt_contest`, and `encrypt_selection` in the tests. 

For example `test_tally.py` and `test_ballot_box.py`. I would do a search in the test folder and just make corrections there the same as the existing ones you've made.

**Comment by phershbe** [comment]
@keithrfung Awesome, I'll have it updated later today.

**Comment by phershbe** [comment]
@keithrfung Okay everything should be updated. I updated tests in cases of "succeeds" but not cases of "fails" because I noticed that some cases of "fails" already had should_verify_proofs=False. There was also an encrypt_ballot in unit/test_ballot_compact.py but the parameters looked different from the other tests so I didn't make the change there. The make test and make auto-lint passed on my newest changes. I'm learning a lot, hopefully the work that I've done is okay. Let me know if I need to do anything else here.

**Comment by keithrfung** [comment]
> [CLA assistant check](https://cla.opensource.microsoft.com/microsoft/electionguard-python?pullRequest=603) Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/electionguard-python?pullRequest=603) before we can accept your contribution.❌ phershbe [sign now](https://cla.opensource.microsoft.com/microsoft/electionguard-python?pullRequest=603)You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/microsoft/electionguard-python?pullRequest=603) it.

You need to sign this btw.

**Comment by phershbe** [comment]
@keithrfung Yeah I had signed the Contributor License Agreement already some days ago. Clicking "recheck" didn't seem to do anything. I signed it again and it seems to be okay now.

**Review by keithrfung — APPROVED** [review]

**Pull request merged**
