### PR TITLE
Fix guardian = 0 in test_end_to_end_election

### LINKED ISSUE #335: test_end_to_end_election is using guardian sequence_order = 0.
Guardian sequence_order must be > 0.

### PR DESCRIPTION
**Pull request by JohnLCaron**
Fixes #335

Guardian sequence_order must be > 0.

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/electionguard-python/336)

### CODE REVIEW

**Review by keithrfung — CHANGES_REQUESTED** [review]
One line change so easy to review. 
1. Linter needs to pass. `make auto-lint`
2. Do you think this should be sitting at the guardian level itself? Maybe just check at that level and never allow a `0`? It's an easy check in python with a setter.

**Comment by JohnLCaron** [comment]
I agree that there should be a check in the Guardian to not allow sequence <= 0. If you want I can add here. But not sure what is the cleanest syntax for that in python.

**Comment by keithrfung** [comment]
@AddressXception I think this should be a `ValueError` on the Guardian constructor. What do you think of this?

https://github.com/microsoft/electionguard-python/blob/22663821cc83e1d3fdaaec3079b8c9dcff0d0b1e/src/electionguard/guardian.py#L104

```py
MIN_SEQUENCE_ORDER  =  1
SEQUENCE_ORDER_ERROR = f"Sequence Order must be at least {MIN_SEQUENCE_ORDER}"

if sequence_order <  MIN_SEQUENCE_ORDER:
     throw ValueError(SEQUENCE_ORDER_ERROR)
```

**Comment by keithrfung** [comment]
@JohnLCaron Can you revisit this?

**Comment by JohnLCaron** [comment]
Yes, sorry, my python installation got mangled and I havent made it back to fixing it.

**Comment by keithrfung** [comment]
@JohnLCaron I actually rolled this fix into the Key Ceremony fix since I created a helper method to ensure this doesn't crop up again.

**Comment by keithrfung** [comment]
I'll close the issue once the integration branch is merged in.

**Comment by JohnLCaron** [comment]
thanks, keith.

**Pull request closed without merging**
