### PR TITLE
Fix super() call in ballot.py related to DeprecationWarning

### LINKED ISSUE #488: 🔧  Fix DeprecationWarning on NotImplemented on ballot.py
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Suggestion

`ballot.py` produces this warning when running `test_compact_submitted_ballot`. This issue is to resolve not ignore the warning.

```
=============================== warnings summary ===============================
tests/unit/test_ballot_compact.py::TestCompactBallot::test_compact_submitted_ballot
  /home/runner/work/electionguard-python/electionguard-python/src/electionguard/ballot.py:852: DeprecationWarning: NotImplemented should not be used in a boolean context
    isinstance(other, SubmittedBallot)
```

This can be seen when running `make test`

### Possible Implementation

_No response_

### Anything else?

_No response_

### LINKED ISSUE #491: 🐞  Expanded Submitted Ballot from Compact includes nonces
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

With the current implementation of Compact Ballot, submitted ballots are correctly constructed but include information that is not typically included. 

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Environment

```markdown
- OS:
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by sha016**
[//]: # (🚨 Please review the CONTRIBUTING.md in this repository. 💔Thank you!)

### Issue

Fixes #488 
Fixes #491 

### Description

fixed super() call on __eq__ on line 853 of ballot.py, which were raising DeprecationWarning and NotImplemented.

### Testing
Run test_ballot_compact.py unit test. However, now it fails `line 91, in test_compact_submitted_ballot` apparently due to the nonce of submitted ballot (None) not matching the nonce of other (expanded ballot). I am submitting as a WIP. Please let me know what the tests are expected to do and the changes to the test that should be made. Can I force push any amendments or?

Thanks in advance.

### CODE REVIEW

**Review by keithrfung — CHANGES_REQUESTED** [review]
Failed the linter

**Comment by sha016** [comment]
@keithrfung now passing pylint. Still fails `test_ballot_compact.py` though, unsure what to do about it since the fail seems correct.

**Comment by keithrfung** [comment]
@sha016 I'm looking into this. I'm not quite sure what this is either.

**Comment by ronnie-llamado** [comment]
Hope it's okay if I add a quick take on this. I think the issue lies in the comparison of the nonces. 

With the super call fixed in this PR, `CiphertextBallot.__eq__` will be checked on `self.submitted_ballot` and `expanded_ballot` in `TestCompactBallot.test_compact_submitted_ballot`.

https://github.com/microsoft/electionguard-python/blob/dcdcdcc3cbd9ca94f9b4437807a99c92054c7923/src/electionguard/ballot.py#L700-L712

--- 

`self.submitted_ballot` is created using `from_ciphertext_ballot` which removes all of the nonces. 

https://github.com/microsoft/electionguard-python/blob/dcdcdcc3cbd9ca94f9b4437807a99c92054c7923/tests/unit/test_ballot_compact.py#L50-L52

https://github.com/microsoft/electionguard-python/blob/dcdcdcc3cbd9ca94f9b4437807a99c92054c7923/src/electionguard/ballot.py#L976-L991

--- 

On the other side of the comparison, `expanded_ballot` will generate a `SubmittedBallot` with the nonces included.

https://github.com/microsoft/electionguard-python/blob/dcdcdcc3cbd9ca94f9b4437807a99c92054c7923/tests/unit/test_ballot_compact.py#L85-L87

https://github.com/microsoft/electionguard-python/blob/dcdcdcc3cbd9ca94f9b4437807a99c92054c7923/src/electionguard/ballot_compact.py#L77-L115

--- 

I threw in a quick assert and found the nonces were not equal. As expected, `self.submitted_ballot` had `None` for its nonce. 
```python
================================== FAILURES ==================================
______________ TestCompactBallot.test_compact_submitted_ballot _______________

self = <tests.unit.test_ballot_compact.TestCompactBallot testMethod=test_compact_submitted_ballot>

    def test_compact_submitted_ballot(self) -> None:
        # Act
        compact_ballot = compress_submitted_ballot(
            self.submitted_ballot, self.plaintext_ballot, self.ballot_nonce
        )
    
        # Assert
        self.assertIsNotNone(compact_ballot)
        self.assertEqual(
            self.submitted_ballot.object_id,
            compact_ballot.compact_plaintext_ballot.object_id,
        )
    
        # Act
        expanded_ballot = expand_compact_submitted_ballot(
            compact_ballot, self.internal_manifest, self.context
        )
    
        # Assert
        self.assertIsNotNone(expanded_ballot)
>       self.assertEqual(self.submitted_ballot.nonce, expanded_ballot.nonce)
E       AssertionError: None != 46504

tests/unit/test_ballot_compact.py:91: AssertionError
```

--- 

This will also be seen when comparing the `contests` between `self.submitted_ballot` and `expanded_ballot` inside `CiphertextBallot.__eq__`.

Here's one example:
```
CiphertextBallotSelection(object_id='some-object-id-affirmative', sequence_order=0, description_hash=51889, ciphertext=ElGamalCiphertext(pad=441744857150689369, data=12771416561607559325), crypto_hash=38664, is_placeholder_selection=False, nonce=None,  proof=DisjunctiveChaumPedersenProof(proof_zero_pad=8345726427492647007, proof_zero_data=10721120983701395475, proof_one_pad=15704665377858422869, proof_one_data=6490362240590821329, proof_zero_challenge=19517, proof_one_challenge=54697, challenge=8693, proof_zero_response=23505, proof_one_response=52451, usage=<ProofUsage.SelectionValue: "Prove selection's value (0 or 1)">), extended_data=None)
CiphertextBallotSelection(object_id='some-object-id-affirmative', sequence_order=0, description_hash=51889, ciphertext=ElGamalCiphertext(pad=441744857150689369, data=12771416561607559325), crypto_hash=38664, is_placeholder_selection=False, nonce=24238, proof=DisjunctiveChaumPedersenProof(proof_zero_pad=8345726427492647007, proof_zero_data=10721120983701395475, proof_one_pad=15704665377858422869, proof_one_data=6490362240590821329, proof_zero_challenge=19517, proof_one_challenge=54697, challenge=8693, proof_zero_response=23505, proof_one_response=52451, usage=<ProofUsage.SelectionValue: "Prove selection's value (0 or 1)">), extended_data=None)
```

**Comment by sha016** [comment]
Thanks @ronnie-llamado , I didn't know the nonce was intentionally removed in `from_ciphertext_ballot`. 

Seems like the assertEqual on line 91 needs to be modified so that it can check equality apart from the nonce. @keithrfung what do you think?

**Comment by keithrfung** [comment]
@ronnie-llamado Excellent breakdown of the problem. 

@sha016 I think it's more than just changing the equality statement. I believe what we may actually want is the nonce for compact ballots to be removed when expanding to a submitted ballot. 

https://github.com/microsoft/electionguard-python/blob/dcdcdcc3cbd9ca94f9b4437807a99c92054c7923/src/electionguard/ballot_compact.py#L113
This line should likely be setting this to None. 

Perhaps an issue should be created to ensure this constructor always sets this to None.

**Comment by ronnie-llamado** [comment]
@keithrfung On top of ensuring that `SubmittedBallot` has `None` for its nonce, all of the `contests` contained in the ballot will need their respective nonces set to `None`.

Using `make_ciphertext_submitted_ballot` to generate the returned `SubmittedBallot` inside `expand_compact_submitted_ballot` should resolve all the nonces.

https://github.com/microsoft/electionguard-python/blob/dcdcdcc3cbd9ca94f9b4437807a99c92054c7923/src/electionguard/ballot.py#L919-L973

**Comment by keithrfung** [comment]
@ronnie-llamado I think this is the 100% the right direction.

**Comment by sha016** [comment]
@keithrfung With the change that @ronnie-llamado suggested the tests now all pass. I've amended my PR

**Review by keithrfung — APPROVED** [review]
Great work @sha016 and @ronnie-llamado !
This solves two bugs so I added another issue to this ticket. 
We appreciate all the hard work!

**Comment by sha016** [comment]
Thank you @keithrfung . Would you mind marking this hacktoberfest-accepted? it was still going on when I created the PR

**Pull request merged**
