### PR TITLE
Added "Repo-Relative Link"

### PR DESCRIPTION
**Pull request by Pradumnasaraf**
[//]: # (🚨 Please review the CONTRIBUTING.md in this repository. 💔Thank you!)
### Description
Fixes - #466 
**Added "Repo-Relative Link" in README.md file so it will be easy to navigate and get inside into files/folder**

**Before Changes**

**After Changes**

### CODE REVIEW

**Comment by Pradumnasaraf** [comment]
Looks like need approval from your side :) @keithrfung

**Comment by keithrfung** [comment]
@Pradumnasaraf Yes. All our pull requests require approval from within.

**Comment by Pradumnasaraf** [comment]
> I like this adjustment but if you're updating please include some of the newer folders. Particularly `data`, `packages`, and `src/electionguard_verifier`

Done, I Have opened an issue for that, but I dint get this second point can you explain a little bit?. @keithrfung

**Comment by Pradumnasaraf** [comment]
@keithrfung Done, opened an issue for that #464  and changes that you prescribe :)

**Pull request merged**
