### PR TITLE
Fix publish results_directory argument

### LINKED ISSUE #258: Publish incorrectly computes the directory in project directory instead of passed in directory
In [publish.py](https://github.com/microsoft/electionguard-python/blob/main/src/electionguard/publish.py), all DEVICES_DIR etc are computed at module evalution time which causes DEVICES_DIR in publish to be "results/devices" even when passing a results_directory different from the default: "results".

I've [hacked cwd in our open source multitenant electionguard platform](https://gitlab.com/electisNGO/electeez/-/blob/master/djelectionguard/views.py#L229-254), but fixing results_directory would be nice, I'd like to make a PR if you don't mind.

### PR DESCRIPTION
**Pull request by jpic**
### Issue

Fixes #258

### Description

In publish(), compute directories during runtime rather than import time, to fix the results_directory argument.

### Testing

Try setting the last argument of publish(), results_directory, which is what the tests now do.

💚Thank you!

### CODE REVIEW

**Comment by keithrfung** [comment]
This is looking really good. Don't worry about Windows Build. #263 will handle that.

**Comment by keithrfung** [comment]
Also I'm gonna change this to a draft PR instead of labeling it as WIP.

**Comment by jpic** [comment]
Thank you @keithrfung, it's ready for review. Didn't find how to convert it back from Draft, sorry about that.

**Review by keithrfung — APPROVED** [review]

**Pull request merged**
