### PR TITLE
Minor errors in trogdar release fixed

### LINKED ISSUE #369: Minor errors in trogdar release
## Still Remaining

1. 
In **decryption.py** at line 414:

    if recovery_public_key is None:

recovery_public_key is not Optional, or null, so test is unneeded?

2. 
In **decryption_mediator.py** at line 218:

      if reconstruct_decryption_share is None:

 reconstruct_decryption_share is not Optional, or null, so test is unneeded?
 
 3. 
 In **decryption_mediator.py** at line 256:

      if reconstructed_share is None:

 reconstructed_share is not Optional, or null, so test is unneeded?
 
4. 
In **decryption_helper.py** at line 125:

     if tally_share:

 tally_share is Optional, so should be:
 
      if tally_share is None:
      

## Completed
5. 
In **guardian.py** at line 490:

    def share_other_guardian_key(self, guardian_id: GUARDIAN_ID) -> ElectionPublicKey:
        """Share other guardians keys shared during key ceremony"""
        return get_optional(self._guardian_election_public_keys.get(guardian_id))

 should return an Optional:
 
    def share_other_guardian_key(self, guardian_id: GUARDIAN_ID) -> Optional[ElectionPublicKey]:
         """Share other guardians keys shared during key ceremony"""
        return self._guardian_election_public_keys.get(guardian_id)
        
 However, this method does not appear to be used anywhere.    
 
 6. 
 In **test_end_to_end_election.py** at line 248:

                    verification = (
                        designated_guardian.verify_election_partial_key_backup(
                            backup_owner.id, identity_auxiliary_encrypt
                        )

 should be:
 
                    verification = (
                        designated_guardian.verify_election_partial_key_backup(
                            backup_owner.id, identity_auxiliary_decrypt
                        )

### PR DESCRIPTION
**Pull request by soham4abc**
_🚨 Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository._

*Link your PR to an issue*

Fixes #369 

### Description
Did the changes as per request in the described issue.

### CODE REVIEW

**Comment by AddressXception** [comment]
changes look good but the linter is failing.  I'm ok with no changing the superfluous none checks, but I do think we should [add this change as well](https://github.com/microsoft/electionguard-python/issues/369#issuecomment-843245275) as part of this PR.

**Comment by soham4abc** [comment]
> changes look good but the linter is failing. I'm ok with no changing the superfluous none checks, but I do think we should [add this change as well](https://github.com/microsoft/electionguard-python/issues/369#issuecomment-843245275) as part of this PR.

I am on it

**Comment by soham4abc** [comment]
> changes look good but the linter is failing. I'm ok with no changing the superfluous none checks, but I do think we should [add this change as well](https://github.com/microsoft/electionguard-python/issues/369#issuecomment-843245275) as part of this PR.

I am have trouble to understand what does the above mentioned comment actually want me to change. Would be helpful if someone clears my doubt . Change in `test_key_ceremony.py`

**Comment by SteveMaier-IRT** [comment]
> > changes look good but the linter is failing. I'm ok with no changing the superfluous none checks, but I do think we should [add this change as well](https://github.com/microsoft/electionguard-python/issues/369#issuecomment-843245275) as part of this PR.
> 
> I am have trouble to understand what does the above mentioned comment actually want me to change. Would be helpful if someone clears my doubt . Change in `test_key_ceremony.py`

If you run:
`poetry run black .`

and then check in the edits, it will reformat some of the whitespace in those 2 files.  The check is looking to make sure that the code is in a consistent format.

**Comment by soham4abc** [comment]
> > > changes look good but the linter is failing. I'm ok with no changing the superfluous none checks, but I do think we should [add this change as well](https://github.com/microsoft/electionguard-python/issues/369#issuecomment-843245275) as part of this PR.
> > 
> > 
> > I am have trouble to understand what does the above mentioned comment actually want me to change. Would be helpful if someone clears my doubt . Change in `test_key_ceremony.py`
> 
> If you run:
> `poetry run black .`
> 
> and then check in the edits, it will reformat some of the whitespace in those 2 files. The check is looking to make sure that the code is in a consistent format.

I did run the command and updated the fork Please do have a look!

**Comment by soham4abc** [comment]
@SteveMaier-IRT  @AddressXception  Please do have a look I did run the linters and the code has reformatted correctly please do leave a review! The checks should pass!

**Comment by soham4abc** [comment]
@keithrfung  any changes required?

**Comment by keithrfung** [comment]
Going to merge this but there are still some items not fixed with the issue so keeping it open.

**Review by keithrfung — APPROVED** [review]

**Pull request merged**
